### ISSUE TITLE
Enhancement: SVG has incorrect color on mouse over

### ISSUE THREAD

**Issue by stdoma** [srobotta/moodle-datafield_email#1]
Hi!
I am currently testing the plugin (Moodle 4.1.9).
I think that the plugin can help some people. Thanks for the work.

When using it, I notice that the SVG in the selection menu has a different color to all other icons when you hover over the entry with the mouse.
I have seen that a fa-icon is used for all other elements.
I'm not yet far enough into the topic to have an overview of everything. At first I only noticed that the icons / gif files that are located in the collection folder are not used.

If I do not place the icon in the folder, a string is displayed.
In the code, I have read something about a fallback to a fa-icon. Does this mechanism work?

![email-icon-display](https://github.com/srobotta/moodle-datafield_email/assets/92015860/37a47602-5f90-4935-a99b-57449950e26a)

**Comment by srobotta** [comment]
Thank you for our comment.
If the icon is copied to the mod/data/pix/field/ folder, the shipped svg icon within the plugin is used. That's how it looks on the left and center column in your screenshot.
If for some reason you didn't copy the icon, a fallback using and already installed fontawesome icon is used. This has the black color and doesn't fit well into the layout. Furthermore there is an issue in the drop down selection when creating a new field. Moodle doesn't use the class method of the field class, that points to the icon. Instead it checks for a png in the folder mentioned above. Because of the missing file, the content of the alt attribute is shown (screen on the right).
Once the field is created and the field list of your database is displayed the icon method in the field class is used and displays the icon (in this case the font awesome icon - I will change that the plugin icon will be used).

**Comment by srobotta** [comment]
This has been generally fixed, because the install process now copies the custom icon at the correct location and the fallback from font awesome is not used anymore.
